### ISSUE TITLE
pod 管理方式

### ISSUE THREAD

**Issue by tbxark** [jpush/jpush-ios-sdk-pod#13]
能不能不要直接把二进制包放在 github 上, 在曹县更新到哭了. 直接放在 cdn 上吧

**Comment by huangminlinux** [comment]
二进制包官网上有，https://www.jiguang.cn/downloads/sdk/ios/

**Comment by tbxark** [comment]
我知道二进制包官网有啊, 但是我要用 pod 进行版本控制啊, 像 bugly,  mob 或者 umeng 都是将二进制包放在 cdn 上 用 zip 的方式应用. 用 git 管理虽然方便, 但是考虑到我国的网络环境这样太不友好了.

**Comment by huangminlinux** [comment]
pod 安装 应该是走的 trunk 服务器，不是直接走github。

**Comment by tbxark** [comment]
trunk 只是提交 podspec 文件, 但是 jpush 的 s.source 是指向 github 的, 所以下载 sdk 还是从 github 上下载

![46401ae2-dce0-40a7-9f63-d9e111f1c5d2](https://cloud.githubusercontent.com/assets/9513891/21107628/5773ac12-c0cd-11e6-8cff-ee768ab8b0b2.png)


![29151ea5-9a7d-4381-b2e1-f00427633f95](https://cloud.githubusercontent.com/assets/9513891/21107635/5da50ffe-c0cd-11e6-962b-1e5e9ccd3a42.png)

**Comment by huangminlinux** [comment]
原先我也是这么觉得的

这个 source 应该只是用来 pod trunk push 的时候拉取到他的 trunk 服务器的地址，

我试过把 github 的指定 tag，删除还是能够正常安装

**Comment by tbxark** [comment]
你应该删除的是 release 不是 tag 吧

**Comment by tbxark** [comment]
因为前段由于代理不稳定, 升级安装 jpush 花了很长的时间,  所以就提了一下意见, 如果能采纳那就太棒了.

**Comment by huangminlinux** [comment]
是tag ，，你可以做个实验。

**Comment by huangminlinux** [comment]
解决速度慢的问题，你可以找找cocoapods 有没有国内的镜像源

**Comment by tbxark** [comment]
cocoapods specs 镜像就有, 我自己都弄了一个,  对 cocoapods 就不可能了.

**Comment by huangminlinux** [comment]
我这边又试了一下， 确实是直接在 source 拉去库，之前删除 tag 之所以还会安装成功估计是缓存问题。

下个版本源会指定到 code 。 

感谢建议
