### ISSUE TITLE
pod spec lint fail， when build xcodebuild in i386 - JPush

### ISSUE THREAD

**Issue by AliceHome** [jpush/jpush-ios-sdk-pod#17]
The following build commands failed:

App-amxqtjqhpnvkgbfycrmkvbpwnsti/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386
(1 failure)

**Comment by AliceHome** [comment]
我是想将JPush封装成一个私有库，结果在验证的时候因为JPush的.a 不支持i386导致验证不通过，有解决的吗？

**Comment by huangminlinux** [comment]
如果是需要 jpush 这个库，直接使用 本库就可以了，

如果是你自己的库，需要引用到 jpush 库，则需要把你的库中的 i386 架构部分删除，这让才能过 cocoapod 的测试

**Comment by AliceHome** [comment]
"lipo libLYPushService.a -remove i386  -output libLYPushService.a" 通过这条命令我可以删除自己库里的 i386 结构，但是每次执行 “pod spec lint --use-libraries --allow-warnings --verbose” 这个验证的时候libLYPushService.a 就会重新编译生成一个新的，可以说一下如何删除库里的 i386 架构部分吗，谢谢？

**Comment by huangminlinux** [comment]
通过源码编译指定架构的 lib  也可以。

**Comment by chaiweiwei** [comment]
指定支持的框架即可：
```
s.xcconfig = {
    'VALID_ARCHS' =>  'arm64 x86_64',
  }
```

**Comment by Spaino** [comment]
> 指定支持的框架即可：
> 
> ```
> s.xcconfig = {
>     'VALID_ARCHS' =>  'arm64 x86_64',
>   }
> ```

感谢你呀!!
