### ISSUE TITLE
请升级到 1.8.2

### ISSUE THREAD

**Issue by summerblue** [jpush/jpush-ios-sdk-pod#2]
[官网下载](http://docs.jpush.cn/display/dev/iOS) 的是 1.8.2 , 而这里的还是 1.8.1, 请更新. 

![image](https://cloud.githubusercontent.com/assets/324764/5586422/4db6ba6c-9108-11e4-8409-5f8882aff987.png)

![image](https://cloud.githubusercontent.com/assets/324764/5586424/5d46328c-9108-11e4-9c47-e23391ae9118.png)

**Comment by javenfang** [comment]
现在更新了版本。
之前的版本的确维护得不及时。
