### ISSUE TITLE
关于jpush 2.1.0版本

### ISSUE THREAD

**Issue by leiyong316** [jpush/jpush-ios-sdk-pod#3]
@javenfang  你好，  在使用2.1.0版本的时候遇到一个问题。 麻烦请支持下。

比如在A手机登录的时候，在用户登录的成功时候设置了alias . [JPUSHService setTags:nil alias:userId callbackSelector:nil target:nil];  每个用户都有自己的userid.
然后后台根据alias推送是可以收到的。 到这里一切都是正常的。

从A手机退出登录，取消了关联别名，调用  [JPUSHService setTags:nil alias:@"" callbackSelector:nil target:nil];   同样的用户在B手机上登录， 因为用户相同所以userid是一样的。。后台再根据alias推送的时候， 收到推送消息的还是A手机。

谢谢

**Comment by javenfang** [comment]
我们来看看这个问题，建议你以后发到： [极光社区](http://community.jpush.cn)

**Comment by leiyong316** [comment]
好的， 这个问题比较着急， app要上线了。非常感谢支持

**Comment by javenfang** [comment]
你是出现了一次这个情况，还是必然重现？

理论上，A 手机上退出登录成功，B 手机上登录时设置 alias 成功，  基于 alias 推送就应该推送到 B 手机上。  现在看起来是这 2 步有失败。  

正常情况下，可能偶尔失败或者超时（你需要处理 API 调用返回错误），但一般不会出问题。

**Comment by leiyong316** [comment]
必然重现。 我设置的时候看了回调，iResCode为0， iAlias是我的userid。
退出取消关联，iResCode为0， iAlias是空,   到这里应该是没有问题的

**Comment by pikacode** [comment]
你好，麻烦你加下qq57380422，我帮你看一下这个问题。
