### ISSUE TITLE
我集成了最新的2.1.6版本，可是居然报这个错了。

### ISSUE THREAD

**Issue by arden** [jpush/jpush-ios-sdk-pod#4]
我今天用pod集成了这个最新版本，可是编译的时候报下面这个错误，急死了。

ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)

我想是不是因为你们的这个pod里用了
  "xcconfig": {
    "OTHER_LDFLAGS": "-weak_library /usr/lib/libz.dylib"
  }
这个引起的。另外我建的是swift工程项目。

**Comment by huangminlinux** [comment]
是有这个问题， 你那边可以先把bitcode 关掉使用，我这边再处理一下

**Comment by arden** [comment]
好的，不过如果这个问题最好可以有办法解决，而不是关闭bitcode，因为大多数时候bitcode这个功能还是需要的。

**Comment by huangminlinux** [comment]
cocoapod 已更新   ，可以执行  pod install 重新安装解决这个问题。已经可以使用bitcode ，  感谢你的bug反馈

**Comment by arden** [comment]
好的，谢谢。

**Comment by arden** [comment]
对了，Pod之后，我还要手动把其它依赖库添加进来吗？比如：SystemConfiguration 这些个库等。

**Comment by huangminlinux** [comment]
使用cocoapod 自动会添加
