### ISSUE TITLE
iOS手机版本，php的jpush SDK服务器推送两个appkey，两个程序刚进入后台都可以收到推送，几分钟后，一个就不能收到了

### ISSUE THREAD

**Issue by blacknes** [jpush/jpush-ios-sdk-pod#5]
PHP 服务器推送消息给两个APPKEY，也就是两个iOS应用程序（A、B），相同的消息，应用程序刚开始进入后台的时候。两个都可以正常收到推送。服务器php也打印出 推送成功。但是过 几分钟之后，再次使用php服务器推送消息。只有一个应用程序A可以收到。另一个应用程序B无法收到推送消息。但是php服务器上的显示依然是成功了，A和B的appkey的 isOK 都是true。但是消息却没有推送过来。然后用jpush的控制台。测试发送通知，却可以收到，请帮忙看下问题出在哪里。谢谢

**Comment by huangminlinux** [comment]
JPush SDK 的相关问题 请在 https://community.jiguang.cn 这里提问，
