### ISSUE TITLE
pod jpush 2.1.9

### ISSUE THREAD

**Issue by Muscliy** [jpush/jpush-ios-sdk-pod#8]
什么时候上传cocoapods

**Comment by huangminlinux** [comment]
-> JPush-iOS-SDK (2.1.9)
   JPush SDK for iOS.极光推送，使得开发者可以即时地向其应用程序的用户推送通知或者消息，与用户保持互动，从而有效地提高留存率，提升用户体验。平台提供整合了Android推送、iOS推送的统一推送服务。
   pod 'JPush-iOS-SDK', '~> 2.1.9'
- Homepage: http://www.jpush.cn/
- Source:   https://github.com/iosmvn/JPush-iOS-SDK.git
- Versions: 2.1.9, 2.1.8, 2.1.7, 2.1.6, 2.1.0, 1.8.8, 1.8.7, 1.8.5, 1.8.4, 1.8.3.1, 1.8.3 [master repo]

2.1.9 已经更新有段时间了，

如果。pod search jpush 发现没有。 2.1.9 的话执行。这段命令 pod repo update master 来更新本地库
