### ISSUE TITLE
pod 2.2.0版本 编译报错_dns_parse_resource_record问题

### ISSUE THREAD

**Issue by devjia** [jpush/jpush-ios-sdk-pod#9]
原因:缺少libresolv.tbd,可在工程手动添加.
根本原因是:
Podfile文件中
libraries里缺少: resolv !!!!!!!!!!!!!!!!
做SDK的人能不能认真点!!!!!!!!!!!!!!

**Comment by huangminlinux** [comment]
非常抱歉，这个问题马上修复

**Comment by huangminlinux** [comment]
已在 2.2.0版本 更新
